[project]
name = "serial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pick>=2.4.0",
    "prompt>=0.4.1",
    "prompt-toolkit>=3.0.51",
    "pyserial>=3.5",
]
